const BAD_REQUEST_CODE = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND_CODE = 404;
const CONFLICT_ERROR = 409;

module.exports = {
  BAD_REQUEST_CODE,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND_CODE,
  CONFLICT_ERROR,
};
